format = """trkBytes [$directory]($style)$character"""


[directory]

truncation_length = 0

truncate_to_repo = false

format = "[$path]($style) "

style = "bold cyan"

home_symbol = "~"

truncation_symbol = "â€¦/"


[character]

success_symbol = "[>](bold green)"

error_symbol = "[>](bold green)"  # Same as success so it's not confusing

